-- ============================================================
-- JJMK b31: supplier bills (daily expense per supplier)
-- run once in Supabase SQL Editor - safe to re-run
-- ============================================================
create table if not exists supplier_bills(
  id         bigint generated by default as identity primary key,
  branch_id  text    not null,
  bill_date  date    not null,
  sup        text    not null,
  amount     numeric not null,
  note       text,
  user_name  text,
  created_at timestamptz default now()
);

alter table supplier_bills enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='supplier_bills' and policyname='spb_rw') then
    create policy spb_rw on supplier_bills for all to anon, authenticated using (true) with check (true);
  end if;
end $$;
grant select, insert, update, delete on public.supplier_bills to anon, authenticated;
grant select on public.supplier_bills to service_role;
do $$ declare s text; begin
  s := pg_get_serial_sequence('public.supplier_bills','id');
  if s is not null then
    execute 'grant usage, select on '||s||' to anon, authenticated';
  end if;
end $$;

select 'supplier_bills' as ok, count(*) from information_schema.tables where table_name='supplier_bills';
